---
title: "Homework 2"
author: "Gustavo Passebon Mendonca"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: yes
  pdf_document:
    toc: yes
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---

------------------------------------------------------------------------

```{r}
#| label: load-libraries
#| echo: false # This option disables the printing of code (only output is displayed).
#| message: false
#| warning: false

library(tidyverse)
library(wbstats)
library(skimr)
library(countrycode)
library(here)
```

```{r}
#| echo: false
#| message: false
#| warning: false


mass_shootings <- read_csv(here::here("data", "mass_shootings.csv"))

glimpse(mass_shootings)
```

```{r}
cases_year=mass_shootings %>% 
  group_by(year) %>% 
  count(year,sort=TRUE)
```

```{r}
cases_race = mass_shootings %>% 
  group_by(race) %>% 
  count(race,sort=TRUE)

ggplot(cases_race, aes(x=race, y = n))+
  geom_col()+
  labs(title="Mass shootings by race",
       x ="Race", y = "Occurrences")+
  geom_text(aes(label = n), vjust = -0.1)
```

```{r}
#Note - do not group the data in the dataframe creation phase when building a boxplot
cases_location = mass_shootings %>% 
  group_by(location_type) 

ggplot(cases_location, aes(x=location_type, y = total_victims))+
  geom_boxplot()

```

```{r}
#Removing the Strip Massacre from the "Case" column
cases_location_vegas = mass_shootings %>%
  filter(case!="Las Vegas Strip massacre") %>% 
  group_by(location_type)
#Redoing the box plot
ggplot(cases_location_vegas, aes(x=location_type, y = total_victims))+
  geom_boxplot()
```

```{r}
#Applying the filters
white_males = mass_shootings %>% 
  filter(year>2000) %>% 
  filter(prior_mental_illness=="Yes") %>% 
  filter(race=="White") %>% 
  count(prior_mental_illness)

#Showing the result
white_males
```

```{r}
#Dataframe to organize the months
months = data.frame(c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),
                    c(1,2,3,4,5,6,7,8,9,10,11,12))
colnames(months) = c("month","Number")
#Filtering and counting the information
cases_month = mass_shootings %>% 
  group_by(month) %>% 
  count(month)

#Joining the two tables
cases_month = left_join(cases_month,months,by="month")

#Ordering the joined table by number of the month
cases_month = cases_month %>% 
  arrange(Number,by_group="Number")

#Plotting
ggplot(cases_month, aes(x=Number, y = n))+
  geom_col()+
  labs(title="Mass shootings by month",
       x ="Month of the year", y = "Occurrences")+
  geom_text(aes(label = n), vjust = -0.5)
```

```{r}
cases_distrib = mass_shootings %>%
  filter(race %in% c("White","Black","Latino")) %>% 
  group_by(race)

ggplot(cases_distrib,aes(x=fatalities,fill=race))+
  geom_histogram(alpha=1,position="dodge")+
  labs(title="Distribution of fatalies by race",
       x ="Fatalities", y = "Occurence")
```

```{r}
mental_distrib = mass_shootings %>% 
  filter(is.na(prior_mental_illness)==FALSE) %>% 
  group_by(prior_mental_illness)
  
mental_location = mass_shootings %>%
  filter(is.na(prior_mental_illness)==FALSE) %>% 
  group_by(prior_mental_illness) %>% 
  count(location_type)

mental_race = mass_shootings %>%
  filter(is.na(prior_mental_illness)==FALSE) %>% 
  filter(is.na(race)==FALSE) %>% 
  group_by(prior_mental_illness) %>% 
  count(race)

ggplot(mental_race,aes(x=race,y=n,fill=prior_mental_illness))+
  geom_col(position = "dodge")
ggplot(mental_distrib,aes(x=age_of_shooter,fill=prior_mental_illness))+
  geom_histogram(alpha=1,position="dodge")

```

```{r}
#Relationship Mental Illness vs Victims
ggplot(mental_distrib,aes(x=total_victims,fill=prior_mental_illness))+
  geom_histogram(alpha=1,position="dodge")

#Relationship Location type vs Mental Illness
ggplot(mental_location,aes(x=location_type,y=n,fill=prior_mental_illness))+
  geom_col(position = "dodge")

#Relationship between the 3 variables
ggplot(mental_distrib,aes(x=location_type,y=total_victims,color=prior_mental_illness))+
  geom_point()
```

```{r}
#| echo: false
#| message: false
#| warning: false

card_fraud <- read_csv(here::here("data", "card_fraud.csv"))

glimpse(card_fraud)
```

```{r}
total_transactions = card_fraud %>% 
  group_by(trans_year) %>%
  count(trans_year,name="transactions")
total_frauds = card_fraud %>%
  filter(is_fraud==1) %>% 
  group_by(trans_year) %>%
  count(is_fraud,name="frauds")
total_frauds = left_join(total_frauds,total_transactions,by="trans_year")
total_frauds %>% 
  mutate(fraud_rate = frauds/transactions)
```

```{r}
card_fraud %>%
  group_by(trans_year,is_fraud) %>% 
  summarize(count = sum(amt))%>%
  ungroup() %>% 
  mutate(is_fraud = ifelse(is_fraud == 1, "fraud", "valid")) %>% 
  pivot_wider(names_from = "is_fraud",values_from = "count") %>% 
  mutate(ratio=fraud/(valid+fraud))
```

```{r}
fraud_hist = card_fraud %>%
  mutate(is_fraud = ifelse(is_fraud == 1, "fraud", "valid"))
  
ggplot(fraud_hist,aes(x=amt,fill=is_fraud))+
  scale_y_continuous(limits=c(0,500))+
  scale_x_continuous(limits=c(0,7000))+
  geom_histogram(alpha=1,position="dodge",binwidth = 50)+
  labs(title="Distribution of fraud amounts",
       x ="Amount in USD", y = "Occurrences")

fraud_hist %>% 
  group_by(is_fraud) %>% 
  summarize(countAmt = n(),meanAmount=mean(amt),medianAmount=median(amt),sdAmt=sd(amt),minAmt=min(amt),maxAmt=max(amt))
```

```{r}
card_fraud %>% 
  group_by(category) %>% 
  count(is_fraud) %>% 
  ungroup() %>% 
  mutate(is_fraud = ifelse(is_fraud == 1, "fraud", "valid")) %>%
  pivot_wider(names_from = "is_fraud",values_from = "n") %>% 
  mutate(ratio=fraud/(valid+fraud)) %>% 
  arrange(desc(ratio))
```

```{r}
fraud_time = card_fraud %>% 
  mutate(
    date_only = lubridate::date(trans_date_trans_time),
    month_name = lubridate::month(trans_date_trans_time, label=TRUE),
    hour = lubridate::hour(trans_date_trans_time),
    weekday = lubridate::wday(trans_date_trans_time, label = TRUE)
  )
#Most common day
fraud_time %>% 
  group_by(weekday) %>% 
  count(weekday,sort=TRUE)
#Most common hour
fraud_time %>% 
  group_by(hour) %>% 
  count(hour,sort=TRUE)
#Most common month
fraud_time %>% 
  group_by(month_name) %>% 
  count(month_name,sort=TRUE)
```

```{r}
#Filtering the data
fraud_age = card_fraud %>%
  mutate(
    age = round(interval(dob, trans_date_trans_time) / years(1)),-1) %>%
  group_by(age) %>% 
  count(is_fraud) %>%
  ungroup() %>% 
  mutate(is_fraud = ifelse(is_fraud == 1, "fraud", "valid")) %>%
  pivot_wider(names_from = "is_fraud",values_from = "n") %>% 
  mutate(ratio=fraud/(valid+fraud))
  
#Ploting the relationship between age and the ratio of fraudulent transactions
ggplot(fraud_age,aes(x=age,y=ratio))+
  geom_col()

#It appears that the occurence of fraud increases with age up to a certain point
```

```{r}
# distance between card holder's home and transaction
# code adapted from https://www.geeksforgeeks.org/program-distance-two-points-earth/amp/


card_fraud <- card_fraud %>%
  mutate(
    
    # convert latitude/longitude to radians
    lat1_radians = lat / 57.29577951,
    lat2_radians = merch_lat / 57.29577951,
    long1_radians = long / 57.29577951,
    long2_radians = merch_long / 57.29577951,
    
    # calculate distance in miles
    distance_miles = 3963.0 * acos((sin(lat1_radians) * sin(lat2_radians)) + cos(lat1_radians) * cos(lat2_radians) * cos(long2_radians - long1_radians)),

    # calculate distance in km
    distance_km = 6377.830272 * acos((sin(lat1_radians) * sin(lat2_radians)) + cos(lat1_radians) * cos(lat2_radians) * cos(long2_radians - long1_radians))

  )

#Filtering
card_fraud$distance_km=round(card_fraud$distance_km,0)
fraud_distance = card_fraud %>%
  group_by(distance_km) %>% 
  count(is_fraud) %>%
  ungroup() %>% 
  mutate(is_fraud = ifelse(is_fraud == 1, "fraud", "valid")) %>%
  pivot_wider(names_from = "is_fraud",values_from = "n") %>% 
  mutate(fraud = ifelse(is.na(fraud)==TRUE, 0, fraud)) %>% 
  mutate(ratio=fraud/(valid+fraud))

#Plotting
ggplot(fraud_distance,aes(x=distance_km,y=ratio))+
  geom_col()

#As it is possible to see, there is a substantial increase in the % of fraudulent cases after 130km
```

```{r}
#| message: false
#| warning: false

# Download electricity data
url <- "https://nyc3.digitaloceanspaces.com/owid-public/data/energy/owid-energy-data.csv"

energy <- read_csv(url) %>% 
  filter(year >= 1990) %>% 
  drop_na(iso_code) %>% 
  select(1:3,
         biofuel = biofuel_electricity,
         coal = coal_electricity,
         gas = gas_electricity,
         hydro = hydro_electricity,
         nuclear = nuclear_electricity,
         oil = oil_electricity,
         other_renewable = other_renewable_exc_biofuel_electricity,
         solar = solar_electricity,
         wind = wind_electricity, 
         electricity_demand,
         electricity_generation,
         net_elec_imports,	# Net electricity imports, measured in terawatt-hours
         energy_per_capita,	# Primary energy consumption per capita, measured in kilowatt-hours	Calculated by Our World in Data based on BP Statistical Review of World Energy and EIA International Energy Data
         energy_per_gdp,	# Energy consumption per unit of GDP. This is measured in kilowatt-hours per 2011 international-$.
         per_capita_electricity, #	Electricity generation per capita, measured in kilowatt-hours
  ) 

# Download data for C02 emissions per capita https://data.worldbank.org/indicator/EN.ATM.CO2E.PC
co2_percap <- wb_data(country = "countries_only", 
                      indicator = "EN.ATM.CO2E.PC", 
                      start_date = 1990, 
                      end_date = 2022,
                      return_wide=FALSE) %>% 
  filter(!is.na(value)) %>% 
  #drop unwanted variables
  select(-c(unit, obs_status, footnote, last_updated)) %>% 
  rename(year = date,
         co2percap = value)


# Download data for GDP per capita  https://data.worldbank.org/indicator/NY.GDP.PCAP.PP.KD
gdp_percap <- wb_data(country = "countries_only", 
                      indicator = "NY.GDP.PCAP.PP.KD", 
                      start_date = 1990, 
                      end_date = 2022,
                      return_wide=FALSE) %>% 
  filter(!is.na(value)) %>% 
  #drop unwanted variables
  select(-c(unit, obs_status, footnote, last_updated)) %>% 
  rename(year = date,
         GDPpercap = value)

#Turning energy into tidy, long format
energy %>% 
  pivot_longer(cols=4:18,names_to = "characteristics",values_to="values")

#Merging the tables
#Selecting the relevant info
co2_percap = co2_percap %>% 
  select(iso3c,year,co2percap)
gdp_percap = gdp_percap %>% 
  select(iso3c,year,GDPpercap)
energy_select = energy %>% 
  select(year,iso_code,energy_per_capita)

#Relationship GDP vs CO2 per capita
joint_table = left_join(gdp_percap,co2_percap,by=c("iso3c"="iso3c","year"="year"))
ggplot(joint_table,aes(x=GDPpercap,y=co2percap))+
  geom_point()

#Relationship GDP vs Energy consumption per capita
energy_gdp = left_join(gdp_percap,energy_select,by=c("iso3c"="iso_code","year"="year"))
ggplot(energy_gdp,aes(x=GDPpercap,y=energy_per_capita))+
  geom_point()
```

# Details

-   Who did you collaborate with: No one
-   Approximately how much time did you spend on this problem set: 7 hours
-   What, if anything, gave you the most trouble: -
